#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
    echo -e "\n Please run as root.\n example: sudo bash install_v2ray \n" >&2
    exit 1
fi

apt update -y && apt install python3-pip shadowsocks-libev libcairo2-dev pkg-config python3-dev python3-venv xclip libnotify-bin \
    python3-gi python3-gst-1.0 python-gi-dev cmake g++ build-essential libglib2.0-dev \
    libglib2.0-dev-bin libgstreamer1.0-dev libtool m4 autoconf automake libgirepository1.0-dev \
    gobject-introspection gir1.2-appindicator3-0.1 -y || (echo -e "err: dependencies only .deb " && exit 1)

sh -c "$(wget -qO- https://github.com/v2rayA/v2rayA-installer/raw/main/installer.sh)" @ --with-v2ray
sh -c "$(wget -qO- https://github.com/v2rayA/v2rayA-installer/raw/main/installer.sh)" @ --with-xray
bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-dat-release.sh)
sleep 3

cp v2raya.png /usr/share/icons/hicolor/512x512/apps/

cp v2raya.desktop /usr/share/applications/

cp -r scripts /usr/local/share/v2ray/
cp assets/favicon-32x32.png /usr/local/share/v2ray/

cd /usr/local/share/v2ray/ || echo "bad /usr/local/share/v2ray/"
python3 -m venv venv
source /usr/local/share/v2ray/venv/bin/activate
pip install pystray Pillow PyGObject

chmod -R 755 /usr/local/share/v2ray/venv/
chmod -R 755 /usr/local/share/v2ray/scripts/

v2raya --reset-password

deactivate
