#!/bin/bash
apt install xterm
wget  https://github.com/v2rayA/v2rayA/releases/download/v2.2.4/installer_debian_x64_2.2.4.deb
dpkg -i $(pwd)/installer_debian_x64_2.2.4.deb
bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-dat-release.sh)
sleep 3

rm /usr/share/applications/v2raya.desktop
mv v2raya.desktop /usr/share/applications/
chmod +x /usr/share/applications/v2raya.desktop


