#!/usr/bin/env bash

Color_Off='\033[0m'
Red='\033[0;31m'
Green='\033[0;32m'
Yellow='\033[0;33m'

if [ "$(id -u)" -ne 0 ]; then
    echo -e "\n$Red Please run as root.\n$Green example:$Yellow sudo bash remove_v2ray \n$Color_Off" >&2
    exit 1
fi

/bin/bash /usr/local/share/v2ray/scripts/kill.sh
V2raya_tray_pid=$(pgrep -f 'python3 /usr/local/share/v2ray/scripts/V2rayA')

kill $V2raya_tray_pid 2 &>/dev/null
killall v2ray

rm -f /usr/share/applications/v2raya*
rm -rf /etc/v2raya*
rm -rf /usr/local/bin/v2ray*
rm -rf /usr/local/share/v2ray*
rm -f /etc/sudoers.d/v2raya_no_passwd

systemctl stop v2raya.service
systemctl disable v2raya.service

apt remove --purge v2ray v2raya -y
